symfony_common.bridge:
  path: /bridge/{service}/{method}
  defaults:
    _controller: symfony_common.controller.service_bridge_controller:callAction
  requirements:
    service: '[a-zA-Z0-9_\.-]+'
    method: '[a-zA-Z0-9_]+'
  methods: [POST]
