symfony_common.service_call:
  path: /service/{service}/{method}
  defaults:
    _controller: symfony_common.controller.service_controller:callServiceAction
  requirements:
    service: '[a-zA-Z0-9_\.-]+'
    method: '[a-zA-Z0-9_]+'
  methods: [POST]
