services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Cosmologist\Bundle\SymfonyCommonBundle\Bridge\ServiceBridge:
  Cosmologist\Bundle\SymfonyCommonBundle\Controller\ServiceBridgeController:
