services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Cosmologist\Bundle\SymfonyCommonBundle\Security\Voter\SuperUserRoleVoter:
  Cosmologist\Bundle\SymfonyCommonBundle\Security\SecurityUtils:
  Cosmologist\Bundle\SymfonyCommonBundle\Security\Crypto:
    bind:
      $secret: '%kernel.secret%'
