services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Cosmologist\Bundle\SymfonyCommonBundle\Security\Voter\SuperUserRoleVoter:
  Cosmologist\Bundle\SymfonyCommonBundle\Security\SecurityUtils:
