services:

  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Cosmologist\Bundle\SymfonyCommonBundle\Twig\CommonExtension:

  Cosmologist\Bundle\SymfonyCommonBundle\Twig\PhpExtension:
    arguments:
      - '%symfony_common.twig.php_extension.functions%'
      - '%symfony_common.twig.php_extension.filters%'
